/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tony_J2C */

#ifndef _Included_com_tony_J2C
#define _Included_com_tony_J2C
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tony_J2C
 * Method:    printText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tony_J2C_printText
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
